### ISSUE TITLE
Error when trying to install with Foundry v10.275

### ISSUE THREAD

**Issue by spetzel2020** [spetzel2020/easy-exports#13]
Console shows:
```
foundry.js:2434 Uncaught (in promise) TypeError: Cannot destructure property 'active' of 'data' as it is null.
    at new Module (foundry.js:2434:12)
    at done (setup.js:325:19)
    at progress (setup.js:346:45)
    at setup.js:602:43
    at Array.forEach (<anonymous>)
    at i._onProgress (setup.js:602:30)
    at x.emit (index.mjs:136:20)
    at i.value (socket.js:278:20)
    at i.value (socket.js:265:18)
    at i.value (socket.js:235:22)
```

**Comment by spetzel2020** [comment]
Cannot reproduce with Easy Exports 0.7.0 and Foundry 10.286
